// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfnduuukuhfcgrlgcysr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmbmR1dXVrdWhmY2dybGdjeXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyOTU0MzUsImV4cCI6MjA1Mjg3MTQzNX0.Hipf-EgKjuqcYR1sdhKfsxAWdJDm4H7TZxlGqwmTZK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);